version: '3.9'

services:
  frontend:
    container_name: frontend
    build:
      context: ./next
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./next/.env:/next/.env
      - ./next/:/next/
      - /next/node_modules
      - /next/.next

  platform:
    container_name: platform
    build:
      context: ./platform
      target: prod
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./platform:/app/src/
    env_file:
      - next/.env
    environment:
      AIFLOW_PLATFORM_HOST: 0.0.0.0
      AIFLOW_PLATFORM_DB_HOST: aiflow_db
      AIFLOW_PLATFORM_DB_PORT: "3307"
      AIFLOW_PLATFORM_DB_USER: "aiflow_platform"
      AIFLOW_PLATFORM_DB_PASS: "aiflow_platform"
      AIFLOW_PLATFORM_DB_BASE: "aiflow_platform"
      AIFLOW_PLATFORM_OPENAI_API_KEY: ""
    depends_on:
      - aiflow_db

  aiflow_db:
    image: mysql:8.0
    container_name: aiflow_db
    restart: always
    build:
      context: ./db
    ports:
      - "3308:3307"
    environment:
      MYSQL_DATABASE: "aiflow_platform"
      MYSQL_USER: "aiflow_platform"
      MYSQL_PASSWORD: "aiflow_platform"
      MYSQL_ROOT_PASSWORD: "aiflow_platform"
      MYSQL_TCP_PORT: 3307
    volumes:
      - aiflow_db:/var/lib/mysql
    command: [ 'mysqld', '--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci' ]

volumes:
  aiflow_db:
